<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_As minhas listas_create</name>
   <tag></tag>
   <elementGuidId>a9000e26-c2ec-4ab5-9584-ce2657dea06f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href, '/ListaProdutos/Create')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.create</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=main >> internal:role=link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d6cced7d-d8f5-4327-bb1d-718062502f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>create</value>
      <webElementGuid>955392c1-f3fc-48a3-b50c-5efb03791126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ListaProdutos/Create</value>
      <webElementGuid>2209fa9b-30f0-4ba5-ad2b-1f23621c3bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/main[@class=&quot;pb-3&quot;]/div[@class=&quot;content&quot;]/a[@class=&quot;create&quot;]</value>
      <webElementGuid>d0b722c5-05f1-4f03-925c-7f6ea6fd8c98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ListaProdutos/Create')]</value>
      <webElementGuid>e6ebc96b-e8de-46dc-ad72-387fb1a55fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/a</value>
      <webElementGuid>8a4a1adc-9ff9-4909-bea4-ecdd2e167788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ListaProdutos/Create']</value>
      <webElementGuid>c506fc37-c4d2-46d1-850b-6b47c6159472</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
