<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_As minhas listas_bin</name>
   <tag></tag>
   <elementGuidId>e962725c-1a53-429e-9289-595d59df1251</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href, '/ListaProdutos/Delete/8b0710be-58b6-4380-bf96-d100dc1cbb10')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(5) > .bin</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9872fb84-1c1e-48ed-a57d-29c7d27c5253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bin</value>
      <webElementGuid>9a71994d-7936-4078-bee2-e472a95cfc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ListaProdutos/Delete/8b0710be-58b6-4380-bf96-d100dc1cbb10</value>
      <webElementGuid>3bd2f3f4-cae8-4e29-82a1-cc8650e9fc71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/main[@class=&quot;pb-3&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;item&quot;]/a[@class=&quot;bin&quot;]</value>
      <webElementGuid>dffdea72-da03-4dac-9513-c5d3fc68838d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ListaProdutos/Delete/8b0710be-58b6-4380-bf96-d100dc1cbb10')]</value>
      <webElementGuid>13d6c593-02f5-4004-a177-b3bfd3d12624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a[2]</value>
      <webElementGuid>5329fa3f-b38d-4992-bd77-e26c2d75373a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ListaProdutos/Delete/8b0710be-58b6-4380-bf96-d100dc1cbb10']</value>
      <webElementGuid>8df3ba35-a333-4d70-9820-4d9dd19ae271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ListaProdutos/Delete/c6f1a3eb-b7ef-4cc9-922f-e4a7316e55f6')]</value>
      <webElementGuid>2eab4bb3-22b8-4676-ac9d-d4e305b74b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a[2]</value>
      <webElementGuid>129c3b57-78fd-4d17-82e7-6d7d72eea648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ListaProdutos/Delete/c6f1a3eb-b7ef-4cc9-922f-e4a7316e55f6']</value>
      <webElementGuid>1f030a8b-c254-41a4-9967-c9f475db8467</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
