<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Criar Produtos</name>
   <tag></tag>
   <elementGuidId>0ef4e1a8-d51d-40de-a90a-9132ba549b62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='criar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#criar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Criar Produtos&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f67a0cf2-d845-447f-9b17-3db3d855c862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>criar</value>
      <webElementGuid>c839615f-5520-4cf5-b54f-1ca729fe0801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Produtos/Create</value>
      <webElementGuid>9da1df73-c2de-43e8-8a56-a84d1c525b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Criar Produtos</value>
      <webElementGuid>3c9ec5ff-f5b3-4dc4-99d7-6958cbd4386f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;criar&quot;)</value>
      <webElementGuid>f531cbf8-5062-4587-9492-2e683e11c55d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='criar']</value>
      <webElementGuid>f780ead7-bdaf-45a0-a3eb-ae32fa703851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Criar Produtos')]</value>
      <webElementGuid>b5fc9d56-800f-4c2a-b14b-a26f50bb8bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produtos'])[2]/following::a[1]</value>
      <webElementGuid>69b909a8-57d0-423f-ab89-afcadf98b2fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lojas'])[1]/following::a[1]</value>
      <webElementGuid>17380f9c-2e81-459c-af20-30fc15f85803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produtos Publicados'])[1]/preceding::a[1]</value>
      <webElementGuid>4c40f82f-e7c8-40bb-a1c6-fd5a366b0a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produtos Pendentes'])[1]/preceding::a[2]</value>
      <webElementGuid>7cf07c90-6390-4718-bb0b-3e79f921954e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Criar Produtos']/parent::*</value>
      <webElementGuid>402ab687-8bed-4ba5-8ab6-340e5393a637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Produtos/Create')]</value>
      <webElementGuid>43c195c9-7f74-4882-b2da-6e7fc42f2182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/a</value>
      <webElementGuid>36c2b7d7-68fe-410e-9452-d05b27123e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'criar' and @href = '/Produtos/Create' and (text() = ' Criar Produtos' or . = ' Criar Produtos')]</value>
      <webElementGuid>4860a16f-0547-4c99-a162-31c85c9c4fea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
