<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Produtos Pendentes_img-edit</name>
   <tag></tag>
   <elementGuidId>e9e889cb-e7a4-4d51-8ca1-cd5166355162</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='publicados-products']/div/div/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.img-edit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#publicados-products div >> internal:has-text=&quot;Massa Esparguete Continente 3€/Unit Eliminar Produto Tem certeza que deseja elim&quot;i >> internal:role=link >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cec06609-193b-4550-b289-03e59b443d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-edit</value>
      <webElementGuid>ae9f2811-3362-4f9f-a802-18302df7ddbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Produtos/Edit/1</value>
      <webElementGuid>79a3c4b8-e39a-483a-8ce1-a0f5b33994fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;publicados-products&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;options&quot;]/p[1]/a[@class=&quot;img-edit&quot;]</value>
      <webElementGuid>782ef841-da21-4c7d-a1fa-1c20c62d1dbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='publicados-products']/div/div/p/a</value>
      <webElementGuid>70eb5378-da8a-4d14-a101-ba172b91ce38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Produtos/Edit/1')]</value>
      <webElementGuid>1178bdb1-decf-4157-a65e-e26a7597aea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>c2efcaac-e1e2-4f96-870a-46bfa2b4bbf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Produtos/Edit/1']</value>
      <webElementGuid>1dac0fe8-f337-4997-a065-a3d4390de3dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='publicados-products']/div/div[2]/p/a</value>
      <webElementGuid>707e060d-f3f5-4d88-981a-d6ee095681c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
