<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Produtos Pendentes_floating-button</name>
   <tag></tag>
   <elementGuidId>6035a055-d677-46c8-b1f2-b126a17f6fcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='addPopup()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.floating-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.floating-button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ccb8c83d-10c2-4b48-b600-2f7e3be9b740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addPopup()</value>
      <webElementGuid>7fb33631-9abc-45de-ad00-3d80c0dd74ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-button</value>
      <webElementGuid>96a11fc9-13ae-47a9-bf0d-e2e3a2f01392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/main[@class=&quot;pb-3&quot;]/section[@class=&quot;containers&quot;]/a[@class=&quot;floating-button&quot;]</value>
      <webElementGuid>e6594312-276a-4da8-97de-b04a40f18996</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='addPopup()']</value>
      <webElementGuid>0d59c148-2314-4bf9-afb0-9bc7f326b06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/a</value>
      <webElementGuid>5b6fd706-1876-4279-9cc4-012496078cf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
