<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Produtos Pendentes</name>
   <tag></tag>
   <elementGuidId>2dbca5f7-c908-475e-87de-fc909da1dfa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pendentes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pendentes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Produtos Pendentes&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e1fd43bb-460e-4bad-8f60-23a5d01138be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pendentes</value>
      <webElementGuid>6f19809d-f34c-492e-a1f6-b3341e9a3200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Produtos Pendentes</value>
      <webElementGuid>b7c88d1f-9aca-4b15-9b25-6ad14312973f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pendentes&quot;)</value>
      <webElementGuid>2070ed6e-6cbe-452b-a4b2-4c54e27164d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pendentes']</value>
      <webElementGuid>575a3ac5-3766-4001-a5ff-0a83802ea46e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Produtos Pendentes')]</value>
      <webElementGuid>27d47361-ac0b-4ef0-83c2-5bfb12aac51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produtos Publicados'])[1]/following::a[1]</value>
      <webElementGuid>6197d7df-cf68-4534-acea-471ee50231e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Criar Produtos'])[1]/following::a[2]</value>
      <webElementGuid>fc55d74e-a297-4627-8a91-6f979ad75275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Produtos Pendentes']/parent::*</value>
      <webElementGuid>efdd9280-7efd-4ed4-a170-4a628766db90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/h2/a</value>
      <webElementGuid>95de71bd-8a36-4f29-a65a-0a94e56ab268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pendentes' and (text() = ' Produtos Pendentes' or . = ' Produtos Pendentes')]</value>
      <webElementGuid>db422121-e152-42c2-a8db-a6413f453360</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
