<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Produtos Pendentes_img-edit</name>
   <tag></tag>
   <elementGuidId>e9e889cb-e7a4-4d51-8ca1-cd5166355162</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.img-edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='publicados-products']/div/div[2]/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#publicados-products div >> internal:has-text=&quot;Atum Bom Petisco 1.2€/Unit Eliminar Produto Salvar&quot;i >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>854cb2cb-0583-490b-8a7e-e9929bb8fc64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-edit</value>
      <webElementGuid>f021a5db-6872-4a51-8d91-447a6a79221e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Produtos/Edit/1</value>
      <webElementGuid>c3101dfb-33f2-4270-8ef7-4da8f6a5d592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;publicados-products&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;options&quot;]/p[1]/a[@class=&quot;img-edit&quot;]</value>
      <webElementGuid>76ec37b1-7803-488f-8133-2a65c616ea60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='publicados-products']/div/div[2]/p/a</value>
      <webElementGuid>707e060d-f3f5-4d88-981a-d6ee095681c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Produtos/Edit/1')]</value>
      <webElementGuid>83dac2c0-a0f1-44f7-bc65-64fc8a040b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>e96f663e-3d3a-48de-87c7-881db1920b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Produtos/Edit/1']</value>
      <webElementGuid>b8d85bcf-ed4e-4dfd-9438-86a459b36440</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
