<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Carregar</name>
   <tag></tag>
   <elementGuidId>b2484d96-2cc5-4020-bf51-4af2de52e436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='phase1']/div/div[2]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.insert-file-input > div > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#phase1 div >> internal:has-text=&quot;Logotipo Carregar Nenhum ficheiro escolhido&quot;i >> label</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>229e717d-336c-4091-99af-750c4c1b20ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>Input_Image</value>
      <webElementGuid>f568e398-daab-415a-a8f0-f7fd962667e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Carregar</value>
      <webElementGuid>490d9fbb-22a6-43ca-bf5d-12b3f43ea08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phase1&quot;)/div[@class=&quot;insert-file file-type-image&quot;]/div[@class=&quot;insert-file-input&quot;]/div[1]/label[1]</value>
      <webElementGuid>7fb445ea-7472-4889-a368-e32bbdb59923</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='phase1']/div/div[2]/div/label</value>
      <webElementGuid>a8d712d9-a43d-4e97-9612-648131b56797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logotipo'])[1]/following::label[1]</value>
      <webElementGuid>9144c5c6-a546-4c5a-a76c-8a8b17269c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continuar'])[1]/following::label[1]</value>
      <webElementGuid>d1907748-e360-4e4f-8fb1-cf9cdca727a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nenhum ficheiro escolhido'])[1]/preceding::label[1]</value>
      <webElementGuid>feecde65-dbd7-4faf-80ae-bb4812e5d9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documento de autenticação'])[1]/preceding::label[1]</value>
      <webElementGuid>42835606-dd1e-40c2-a758-ee1508f5d283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Carregar']/parent::*</value>
      <webElementGuid>351e5f20-d322-4fc5-a6df-5d3153f057bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label</value>
      <webElementGuid>e4eb84a3-740d-421b-90c3-fffb40b6dcd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Carregar' or . = 'Carregar')]</value>
      <webElementGuid>f49ed3c8-9420-42ac-a17e-44d43ddf91d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
