<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Morada da Loja Avenida da Liberdade_img-back</name>
   <tag></tag>
   <elementGuidId>4e3d3808-3798-44b6-8119-9ae6942a674f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='showLojas()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.img-back</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#lojas a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>530412db-9c50-48dc-a0d4-a0c63ae92ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-back</value>
      <webElementGuid>28ebfbf6-5a26-4513-a6a5-367728eae28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showLojas()</value>
      <webElementGuid>18cea67d-9547-4bc6-a271-a1c8cc546d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lojas&quot;)/a[@class=&quot;img-back&quot;]</value>
      <webElementGuid>aa8e23ca-a712-4b48-b856-2f4f28fd41da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='showLojas()']</value>
      <webElementGuid>d622fdd5-dc8a-4aba-b154-3fe0fa6f8ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lojas']/a</value>
      <webElementGuid>516d0576-1aaa-44b6-979d-cd531fe0c7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>025270eb-abfa-4b10-b379-d07e0b104994</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
