<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Comerciante_account-type-comerciante-logo</name>
   <tag></tag>
   <elementGuidId>9c0add03-60b3-4496-8ea6-675b0a9fb662</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='login-submit']/span)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.account-type-comerciante-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Comerciante&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6a190ca0-49fa-413d-9b48-58975e9d41d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>account-type-comerciante-logo</value>
      <webElementGuid>147668a7-91d9-417a-b44f-f322c7d72f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;gradiante-main-color background-height&quot;]/div[@class=&quot;container&quot;]/main[@class=&quot;pb-3&quot;]/div[@class=&quot;content-background authentication-box center-div-x-axis&quot;]/div[@class=&quot;centered-content&quot;]/div[@class=&quot;inline-div&quot;]/a[@class=&quot;a-div-button&quot;]/button[@id=&quot;login-submit&quot;]/span[@class=&quot;account-type-comerciante-logo&quot;]</value>
      <webElementGuid>851a7b0d-45bf-40ce-be33-436e1c7679d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//button[@id='login-submit']/span)[2]</value>
      <webElementGuid>77b45ba9-8482-4886-920c-1452de5991ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/button/span</value>
      <webElementGuid>df9dfc7f-ed56-4e13-9911-afaf697502ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
