<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Comerciante_account-type-comerciante-logo</name>
   <tag></tag>
   <elementGuidId>9c0add03-60b3-4496-8ea6-675b0a9fb662</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='login-submit']/span)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.account-type-comerciante-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Comerciante&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>32989880-b33e-451e-b0c2-cb6eb1e54346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>account-type-comerciante-logo</value>
      <webElementGuid>90dda96f-e5db-419c-94b1-d2806a47eff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;gradiante-main-color background-height&quot;]/div[@class=&quot;container&quot;]/main[@class=&quot;pb-3&quot;]/div[@class=&quot;content-background authentication-box center-div-x-axis&quot;]/div[@class=&quot;centered-content&quot;]/div[@class=&quot;inline-div&quot;]/a[@class=&quot;a-div-button&quot;]/button[@id=&quot;login-submit&quot;]/span[@class=&quot;account-type-comerciante-logo&quot;]</value>
      <webElementGuid>3c127edb-163c-483a-9e0f-ca06859244c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//button[@id='login-submit']/span)[2]</value>
      <webElementGuid>6f4b0893-7fae-4edb-84fe-a71b763e9b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/button/span</value>
      <webElementGuid>db23c1a7-01f4-48cf-ad50-bcaf9d34946a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
