<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Agrupamento 1_colapsable-button</name>
   <tag></tag>
   <elementGuidId>b1d8ad65-40ba-49c5-b3d3-a1f846405903</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.colapsable-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-container']/div[3]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.colapsable-button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c52542f9-ca66-4a5a-a209-1dfdccc70c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>colapsable-button</value>
      <webElementGuid>eb1f37ae-8781-4a54-9167-982421e1cedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-container&quot;)/div[@class=&quot;column-container smaller-gap-y&quot;]/div[@class=&quot;background-constrast-color-2 rounded-border&quot;]/div[@class=&quot;colapsable-div smaller-padding&quot;]/button[@class=&quot;colapsable-button&quot;]</value>
      <webElementGuid>49ac3a84-d52a-4a2b-8aca-a32e6785b2ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-container']/div[3]/div/div/button</value>
      <webElementGuid>366613e5-8ccc-40eb-b8d2-4f98f49aba7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>2b9bad42-841f-4a6e-a51b-323be4a5093c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
