<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Eliminar Agrupamento</name>
   <tag></tag>
   <elementGuidId>1177b41c-f44d-44c5-bc32-219750af1f07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[81]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#delete-popup-2 > div.smaller-page.column-container.center-x-flex.center-y-flex.shrink-flex.edges-flex > div.column-container.max-height.edges-flex.max-width > div.row-container.right-flex.max-width > form > div.delete-div.small-padding-right2 > button.pechincha-button.delete-button-color.bigger-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Eliminar Agrupamento&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4d87fc99-2c44-41e3-9c65-a1b2caf98629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pechincha-button delete-button-color bigger-button</value>
      <webElementGuid>79fb32f6-bccc-4ba0-8bab-5288d218d281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0868944f-5654-4438-94aa-629897fb4dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Eliminar Agrupamento</value>
      <webElementGuid>2ebed861-aa43-4a9d-933e-fdc7ed033cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete-popup-2&quot;)/div[@class=&quot;smaller-page column-container center-x-flex center-y-flex shrink-flex edges-flex&quot;]/div[@class=&quot;column-container max-height  edges-flex max-width&quot;]/div[@class=&quot;row-container right-flex max-width&quot;]/form[1]/div[@class=&quot;delete-div  small-padding-right2&quot;]/button[@class=&quot;pechincha-button delete-button-color bigger-button&quot;]</value>
      <webElementGuid>98b4acc0-6bc9-4012-a27c-e85964d8c10a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[81]</value>
      <webElementGuid>35eb85a3-6dd1-4935-bb30-b2daffeac909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='delete-popup-2']/div/div[2]/div[2]/form/div/button</value>
      <webElementGuid>3e38aab7-4380-4dce-9ef4-7895c2a9a8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agrupamento 3'])[2]/following::button[1]</value>
      <webElementGuid>9a8b8b02-b1e4-44d0-b4e0-a60dc9e57c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tem certeza que deseja eliminar este agrupamento?'])[2]/following::button[1]</value>
      <webElementGuid>fede09ee-7585-444e-8dfc-01f4aed05190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nome'])[3]/preceding::button[1]</value>
      <webElementGuid>b7ce0c26-3b4f-47e8-963b-45f725b4cd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Renomear'])[2]/preceding::button[1]</value>
      <webElementGuid>84e364ed-06aa-47b6-bcf1-e1873f4bba8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div/div[2]/div[2]/form/div/button</value>
      <webElementGuid>f48cf204-2425-4fb6-ac0e-36a57a1eb909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Eliminar Agrupamento' or . = ' Eliminar Agrupamento')]</value>
      <webElementGuid>f123a3cf-0150-4adb-97d4-5380b39d6e1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
