<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save_Nome</name>
   <tag></tag>
   <elementGuidId>be235677-19b4-472d-8a21-4885e542bee5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Remover Listas']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.pechincha-button.delete-button-color.medium-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Remover Listas&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac18b9fd-8021-4d05-ad21-f1ab72c98476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5654b381-55da-42bb-9d89-baa286b8de09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Remover Listas</value>
      <webElementGuid>e62aae2d-c228-4d8a-8eda-abac541fd4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pechincha-button delete-button-color medium-button</value>
      <webElementGuid>fff67b03-a41b-4f8c-a1d7-99dfb82748ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formRemoveLists_68e3a148-bd61-42a8-b407-47074303229f&quot;)/input[@class=&quot;pechincha-button delete-button-color medium-button&quot;]</value>
      <webElementGuid>de5ed428-8c29-44f6-a99c-8a14f7a8f6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>formRemoveLists_68e3a148-bd61-42a8-b407-47074303229f</value>
      <webElementGuid>161c14ef-6502-4702-87fa-e43c2f913d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>listasId</value>
      <webElementGuid>1a0909cc-d62c-49e6-bf17-bb598077d724</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Remover Listas']</value>
      <webElementGuid>adf6e6b9-8091-4bb1-8726-2b986cf1d57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRemoveLists_68e3a148-bd61-42a8-b407-47074303229f']/input</value>
      <webElementGuid>7404e0f0-bb00-4020-8468-a6ec83e0f3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/form/input</value>
      <webElementGuid>a5ac97e3-c4df-4a27-b85c-48252f4161ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>64e925e7-dff0-4ba9-b6ce-4ef55cd4b2d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='listasId']</value>
      <webElementGuid>c35d0d95-a747-4b86-a205-e6b499c09610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-container']/div[4]/div/div[2]/div/div[4]/div[3]/div/div/input</value>
      <webElementGuid>83753a36-0e67-4901-9965-018fca602d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>ca5ac0d8-7383-4828-934d-26267770253b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@form = 'formRemoveLists_68e3a148-bd61-42a8-b407-47074303229f' and @type = 'checkbox' and @name = 'listasId']</value>
      <webElementGuid>a2f9d220-be64-4b4e-89fc-131996beae7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Salvar']</value>
      <webElementGuid>2e7ca1f0-24a4-4427-b17f-e9093cf10231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-container']/div[4]/div/div[2]/div/div[3]/form/div[2]/input</value>
      <webElementGuid>3640634e-fcd7-4d34-a833-64d113bb8469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/input</value>
      <webElementGuid>8b7e3254-5b44-41ab-b1b4-c895af6cc853</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
