<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Eliminar Agrupamento</name>
   <tag></tag>
   <elementGuidId>7fd89d3d-30b3-49fd-a8c6-b46684f70ba7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[91]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#delete-popup-2 > div.smaller-page.column-container.center-x-flex.center-y-flex.shrink-flex.edges-flex > div.column-container.max-height.edges-flex.max-width > div.row-container.right-flex.max-width > form > div.delete-div.small-padding-right2 > button.pechincha-button.delete-button-color.bigger-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Eliminar Agrupamento&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0eb4406e-3f8c-448f-87de-1642fdf4dd9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pechincha-button delete-button-color bigger-button</value>
      <webElementGuid>a59d0abe-286a-4cb7-a408-96915d730c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a02776ee-8afa-4a58-b26a-44115fd74d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Eliminar Agrupamento</value>
      <webElementGuid>c2afcbbf-f3e2-4606-8a58-f7a692376ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete-popup-2&quot;)/div[@class=&quot;smaller-page column-container center-x-flex center-y-flex shrink-flex edges-flex&quot;]/div[@class=&quot;column-container max-height  edges-flex max-width&quot;]/div[@class=&quot;row-container right-flex max-width&quot;]/form[1]/div[@class=&quot;delete-div  small-padding-right2&quot;]/button[@class=&quot;pechincha-button delete-button-color bigger-button&quot;]</value>
      <webElementGuid>e6012a73-a88f-4f21-a39b-b13d6f32d26f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[91]</value>
      <webElementGuid>a2218e16-3eef-49fc-9294-d4d0dd1f6b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='delete-popup-2']/div/div[2]/div[2]/form/div/button</value>
      <webElementGuid>c8d878cb-4cf3-422a-808f-06fdd17c2322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agrupamento 3'])[2]/following::button[1]</value>
      <webElementGuid>2ec5abd3-6dfb-48c9-8004-98db57d20c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tem certeza que deseja eliminar este agrupamento?'])[2]/following::button[1]</value>
      <webElementGuid>bb73cbe1-1859-486a-896d-ecd32aaac88a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nome'])[3]/preceding::button[1]</value>
      <webElementGuid>7558fb65-0a12-4adf-8752-97a22816e84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Renomear'])[2]/preceding::button[1]</value>
      <webElementGuid>cb160bb3-c682-4207-98c1-af32eb2cfb4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div/div[2]/div[2]/form/div/button</value>
      <webElementGuid>ae89fb85-a565-4be5-acbd-eb5a0c0bf806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Eliminar Agrupamento' or . = ' Eliminar Agrupamento')]</value>
      <webElementGuid>fbf45b2e-5d17-419d-99cc-a6562bfaaa3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
