<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Criar Agrupamento</name>
   <tag></tag>
   <elementGuidId>6fcfe2aa-9f81-45cb-960d-9cd325b1390b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.pechincha-button.default-button-color.bigger-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Criar Agrupamento&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b670ba20-6db4-4d00-ba2b-459c8cd0315a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pechincha-button default-button-color bigger-button</value>
      <webElementGuid>6b74b27c-65f9-4dfc-86c7-c14162fd75b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ab78efc9-e379-49e0-90ac-fee5cfda1d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Criar Agrupamento</value>
      <webElementGuid>d7e4cc59-56b9-435c-ae5f-83da94d77248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-container&quot;)/div[@class=&quot;display-flex&quot;]/form[@class=&quot;small-padding&quot;]/button[@class=&quot;pechincha-button default-button-color bigger-button&quot;]</value>
      <webElementGuid>e90e43ba-52d1-4246-ba5d-f7c42174c83a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>403e14b6-f5d2-4e6f-8fa1-a1b5cb0f5819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-container']/div/form/button</value>
      <webElementGuid>556cdce5-d3d1-4feb-95f9-9f59f7d47743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agrupamentos'])[2]/following::button[1]</value>
      <webElementGuid>efd3fcde-92fe-4ca1-ae0e-6474c414f4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal data'])[1]/following::button[1]</value>
      <webElementGuid>55c64202-48fb-4f50-9459-f7e613790ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrar Agrupamento'])[1]/preceding::button[1]</value>
      <webElementGuid>792c5ba9-52eb-476d-b351-98ca179f9aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrar num Agrupamento'])[1]/preceding::button[2]</value>
      <webElementGuid>3809fdfa-f23a-45c9-a7a9-eecb7937f852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Criar Agrupamento']/parent::*</value>
      <webElementGuid>1e0dfbc6-3997-4f71-a24a-cc5451d027ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/button</value>
      <webElementGuid>fbd6cd5d-e1d1-4e99-af82-75942e806a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Criar Agrupamento' or . = 'Criar Agrupamento')]</value>
      <webElementGuid>8ac8bebb-81d0-4bd5-a6ef-ae8beff4e841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-container']/form/button</value>
      <webElementGuid>ca310005-3076-45c8-9143-566638c3634d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/button</value>
      <webElementGuid>acfdcd56-c32d-41b4-87b7-e86f3cd2072f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
