<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Adicionar_Membro_Util</name>
   <tag></tag>
   <elementGuidId>dcd36c3b-8b5f-4122-ba50-eb3d710c6283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@value='Save'])[32]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Adicionar Membro&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>41e5a96b-8960-448b-abba-9d38caa8b15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d226f41a-2165-4217-b2cb-6a682388bca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>799ced91-b2d9-4af5-bbc8-2ec66a0c6cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pechincha-button default-button-color medium-button</value>
      <webElementGuid>94dc7488-db2d-48c8-b396-d45f4d3a5276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adicionar Membro</value>
      <webElementGuid>99545aa2-d8ad-4517-be4f-46a818f62667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-member-to-68e3a148-bd61-42a8-b407-47074303229f&quot;)/div[@class=&quot;hoverable-div row-container edges-flex small-padding&quot;]/form[@class=&quot;fit-content-width center-y-flex&quot;]/button[@class=&quot;pechincha-button default-button-color medium-button&quot;]</value>
      <webElementGuid>d316ef5d-aff1-46a7-b9ae-90bf501957f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@value='Save'])[32]</value>
      <webElementGuid>97459694-8951-42c9-9b27-1bca9a8c20c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-member-to-68e3a148-bd61-42a8-b407-47074303229f']/div[30]/form/button</value>
      <webElementGuid>9b0752d1-c15d-4e76-8948-9c5d359f3e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Util'])[1]/following::button[1]</value>
      <webElementGuid>e33fb388-36d6-442f-b049-bae5b8c1020a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adicionar Membro'])[29]/following::button[1]</value>
      <webElementGuid>b1489d98-55f2-40eb-8ca3-c18224f308b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Util'])[2]/preceding::button[1]</value>
      <webElementGuid>fb7a85ff-9083-428c-b6eb-c55c46f0d720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adicionar Membro'])[31]/preceding::button[1]</value>
      <webElementGuid>cf258897-273d-42a4-8a08-3e2d051bfa39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[30]/form/button</value>
      <webElementGuid>838fd8b6-e359-4398-b840-85468d6d9ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Adicionar Membro' or . = 'Adicionar Membro')]</value>
      <webElementGuid>ac7837f1-4f5c-4916-80bb-cfd6493ad63e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
