<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Editar</name>
   <tag></tag>
   <elementGuidId>847f542a-950b-469e-9541-362b181998c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pechincha-button.default-button-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='changeNameEditableField(this)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Editar&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d110552d-699b-4a9c-b451-482f08b9bc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pechincha-button default-button-color</value>
      <webElementGuid>a53095be-7e40-4a1b-9b3c-0e8346a127e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changeNameEditableField(this)</value>
      <webElementGuid>abbe8e4c-d02b-426c-827a-166b8cf40afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Editar</value>
      <webElementGuid>26458cf0-e353-495a-bd0f-8fbd3f1d1bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-container&quot;)/div[@class=&quot;column-container smaller-gap-y&quot;]/div[@class=&quot;background-constrast-color-2 rounded-border&quot;]/div[@class=&quot;small-margin-right small-margin-left small-margin-bottom small-margin-top smaller-gap-y column-container&quot;]/div[@class=&quot;background-constrast-color small-padding rounded-border&quot;]/form[@class=&quot;row-container edges-flex&quot;]/div[@class=&quot;row-container center-y-flex smaller-gap-x&quot;]/div[@class=&quot;pechincha-button default-button-color&quot;]</value>
      <webElementGuid>e7f17c7c-4b4f-4fce-a7a2-7051cb60bb72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='changeNameEditableField(this)']</value>
      <webElementGuid>64eb2198-b170-46da-9162-2a5de8284f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-container']/div/div/div[2]/div/form/div[2]/div</value>
      <webElementGuid>12f41225-108e-4adf-b382-b97fe8ada89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nome'])[1]/following::div[2]</value>
      <webElementGuid>a9913718-3cd6-4427-be93-a98297a43114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agrupamento da família'])[1]/following::div[5]</value>
      <webElementGuid>ac67744c-2791-4c45-9779-df53c214afc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Listas'])[1]/preceding::div[1]</value>
      <webElementGuid>359d0f38-08cd-4157-b3bb-5e85f77a4648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adicionar Lista'])[1]/preceding::div[1]</value>
      <webElementGuid>594c36f6-4457-4ec3-a7ab-d8a030eaaf27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Editar']/parent::*</value>
      <webElementGuid>cc76268f-c430-4358-bc59-060a391c7d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div</value>
      <webElementGuid>3a954969-dd2a-4a4e-8afa-d075596360bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Editar' or . = 'Editar')]</value>
      <webElementGuid>d870fedf-6208-4608-bb2c-b7c238366967</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
