<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lista de Produtos_listaId</name>
   <tag></tag>
   <elementGuidId>b703e2dc-415d-4312-9ae8-d29e5ea10589</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='50fe415d-40d2-41f3-99cd-1325eda32593']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#50fe415d-40d2-41f3-99cd-1325eda32593</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Lista de Janeiro&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15cc3f6b-3137-44fc-9dd7-b18122a10271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>listaId</value>
      <webElementGuid>0dbc326a-d21a-456a-b91b-22d4a7934f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>50fe415d-40d2-41f3-99cd-1325eda32593</value>
      <webElementGuid>15a9de08-0af5-4c84-956e-14e55ae49e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c3fa3c90-2853-47e8-a0ea-050952aa7273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>50fe415d-40d2-41f3-99cd-1325eda32593</value>
      <webElementGuid>e9a6a9b0-e853-4f27-a0f7-510128440104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-list-0&quot;)/div[@class=&quot;big-page column-container center-x-flex center-y-flex shrink-flex edges-flex&quot;]/form[@class=&quot;column-container edges-flex max-width max-height&quot;]/div[@class=&quot;column-container wrap-flex small-gap center-x-flex small-padding-right small-padding-left list-chooser&quot;]/div[1]/input[@id=&quot;50fe415d-40d2-41f3-99cd-1325eda32593&quot;]</value>
      <webElementGuid>84833dd4-8d77-46e2-a451-9d412cbb35a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='50fe415d-40d2-41f3-99cd-1325eda32593']</value>
      <webElementGuid>2f2c20da-bd7f-400b-bcce-3fad070d9781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-list-0']/div/form/div[2]/div/input</value>
      <webElementGuid>87c5aa60-c309-4b35-aa5a-8665c76769dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>1766e831-7294-4dfa-a208-2f34cf2e1060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'listaId' and @id = '50fe415d-40d2-41f3-99cd-1325eda32593' and @type = 'radio']</value>
      <webElementGuid>4b3f8754-d7a1-4e15-8f34-230f89807e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='2580b2ed-c851-4c68-dd90-08dc498e2da8']</value>
      <webElementGuid>6d125002-900c-4b39-98e6-77713fe77fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-list-1']/div/form/div[2]/div/input</value>
      <webElementGuid>0e533b56-866b-489f-9b31-21647d0d0bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/input</value>
      <webElementGuid>ad4be2e2-8319-4c08-a915-5cd89b0de2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'listaId' and @id = '2580b2ed-c851-4c68-dd90-08dc498e2da8' and @type = 'radio']</value>
      <webElementGuid>502c186c-bce9-4011-8902-8dd1dcea0be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='2f2d4795-4173-43c1-822d-3c308d17d1c5']</value>
      <webElementGuid>a866b289-18f1-4ece-b2d6-f44cdc5a4058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'listaId' and @id = '2f2d4795-4173-43c1-822d-3c308d17d1c5' and @type = 'radio']</value>
      <webElementGuid>18a09b7d-517e-458c-98d0-95e9d738e197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c6f1a3eb-b7ef-4cc9-922f-e4a7316e55f6']</value>
      <webElementGuid>809e35a6-1ea2-4b06-962d-bcafb8fe28eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'listaId' and @id = 'c6f1a3eb-b7ef-4cc9-922f-e4a7316e55f6' and @type = 'radio']</value>
      <webElementGuid>a398df1c-a079-4b92-8530-33a2d06e2539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='8b0710be-58b6-4380-bf96-d100dc1cbb10']</value>
      <webElementGuid>b3f5480f-6f30-47e5-87c9-c59f3fb7f475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'listaId' and @id = '8b0710be-58b6-4380-bf96-d100dc1cbb10' and @type = 'radio']</value>
      <webElementGuid>c994b7ec-444c-4e12-afac-30beef9a827e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
