<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Eleminar_Membros</name>
   <tag></tag>
   <elementGuidId>64efe018-77da-4819-b9c0-dd4062384356</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='membros']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;membros&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b3efd7c-e07d-4d9d-8e3d-5366ab3bfb33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>membros</value>
      <webElementGuid>3999cf7d-9248-4cc1-af19-6f2a47bd5e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-button fit-content-width fit-content-height</value>
      <webElementGuid>59aba98a-0133-4699-8c65-ecf3f1437150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>ddfd7715-c4a2-4537-94ad-a360ce818145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Remover Membros</value>
      <webElementGuid>a7c5c59e-3221-47e6-8149-75afe122cbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/recycle-bin.png</value>
      <webElementGuid>c5d791da-cc78-44af-bc22-8ec14eaa0c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formRemove_68e3a148-bd61-42a8-b407-47074303229f&quot;)/input[@class=&quot;img-button fit-content-width fit-content-height&quot;]</value>
      <webElementGuid>7107f8a0-4e37-4a22-9c5d-7242418f1b21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='membros']</value>
      <webElementGuid>b575cb3d-43cf-4c41-a470-74ea704a501e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRemove_68e3a148-bd61-42a8-b407-47074303229f']/input</value>
      <webElementGuid>c8eb42cc-1b22-4089-93f1-eb91ae8f4159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/form/input</value>
      <webElementGuid>5f4aea1c-6334-430d-962e-312bb6c8ff55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'membros' and @type = 'image' and @src = '/images/recycle-bin.png']</value>
      <webElementGuid>ca8caf2a-2c51-471b-9a39-06014c1e9875</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
