<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Selecionar Permisso_members</name>
   <tag></tag>
   <elementGuidId>caf86697-d62f-40af-a19d-3b1ba2b84798</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='members'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=checkbox >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>425fbbe6-c479-4974-a039-7d5b0ced5000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>formRemove_68e3a148-bd61-42a8-b407-47074303229f</value>
      <webElementGuid>f64f807a-612c-4fb3-8780-57ce9273de20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>46ff7e0c-66e4-45f7-a6d0-395642052ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>members</value>
      <webElementGuid>0975beb1-4b5c-490c-a80d-43c42a6a9ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a3b5dc8b-cd4a-4491-6f14-08dc542e5eb9</value>
      <webElementGuid>93592058-0fca-43d6-82b2-c5306c394d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6d4b20c7-9cf8-4b5f-ada9-2693cdc3bfcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>checkTheBox(this,'68e3a148-bd61-42a8-b407-47074303229f')</value>
      <webElementGuid>73fd315b-b7bc-4a73-8def-b3d592578eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-container&quot;)/div[@class=&quot;column-container smaller-gap-y&quot;]/div[@class=&quot;background-constrast-color-2 rounded-border max-width&quot;]/div[@class=&quot;max-width open background-constrast-color-2&quot;]/div[@class=&quot;small-margin-right small-margin-left small-margin-bottom small-margin-top smaller-gap-y column-container&quot;]/div[@class=&quot;background-constrast-color small-padding tiny-gap-y column-container rounded-border&quot;]/div[@class=&quot;row-container edges-flex max-width&quot;]/div[@class=&quot;column-container max-width&quot;]/div[@class=&quot;row-container edges-flex max-width&quot;]/div[@class=&quot;center-y-flex smaller-gap-x&quot;]/input[@class=&quot;checkbox&quot;]</value>
      <webElementGuid>fe1bda59-c4c3-43ed-9649-a064da433c54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='members'])[2]</value>
      <webElementGuid>0e9fb28f-575d-46f0-b1c5-c74d1e14df14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-container']/div[4]/div/div[2]/div/div[5]/div[3]/div/div[3]/div/input</value>
      <webElementGuid>362a5507-8723-4e31-81d8-ca6a27a5c277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>a93d5f74-cc71-47d2-809c-7890271b9dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@form = 'formRemove_68e3a148-bd61-42a8-b407-47074303229f' and @type = 'checkbox' and @name = 'members']</value>
      <webElementGuid>1794e44d-eb30-4909-8009-cd465c8d62d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
