<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_remover_Lista</name>
   <tag></tag>
   <elementGuidId>132d01f3-13b4-4671-bbb7-8f1a931a713d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Remover Listas']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.pechincha-button.delete-button-color.medium-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Remover Listas&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0e29e2d-5bbe-4061-96aa-e3fb71344cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pechincha-button delete-button-color medium-button</value>
      <webElementGuid>4e25b963-140d-4b22-9a13-96a418e462f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>57927c6e-a3d2-4e6a-8ff6-76986808c681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Remover Listas</value>
      <webElementGuid>0a28b23f-2cbf-41a3-8160-f487dd1a591d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formRemoveLists_68e3a148-bd61-42a8-b407-47074303229f&quot;)/input[@class=&quot;pechincha-button delete-button-color medium-button&quot;]</value>
      <webElementGuid>c5b92fd9-92e7-4320-b2b6-0d7500aa1fb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Remover Listas']</value>
      <webElementGuid>d0481452-c537-4c5a-8688-085291b8d2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRemoveLists_68e3a148-bd61-42a8-b407-47074303229f']/input</value>
      <webElementGuid>77b84e0a-1081-4b02-a806-c824bd611ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/form/input</value>
      <webElementGuid>eb51f2dc-72f2-4990-9020-6084f4900696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>20720fe0-e66e-4d96-a30e-56efe2dae5a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
