<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search_member</name>
   <tag></tag>
   <elementGuidId>5c7831f4-925a-4f6d-b8e7-c144d1b89f99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='searchInput'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.small-padding-right.small-padding-left > div.nav-search-div > #searchInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#add-member-0 >> internal:attr=[placeholder=&quot;Pesquisar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e7bd0a1-23a8-4cb4-aaba-397a014409f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de250d2a-50dd-4e6a-9c48-ce16b407ab30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchInput</value>
      <webElementGuid>8e46303e-2e68-4055-bd6a-f48a5b87cc0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchText</value>
      <webElementGuid>d046e95c-8d49-4ca1-840e-f116a6519d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>abfbd9d1-83a4-423a-842e-867297069588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pesquisar</value>
      <webElementGuid>68286c60-5ccd-42c4-8199-879837cabb5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>searchPerson(this.value, '68e3a148-bd61-42a8-b407-47074303229f')</value>
      <webElementGuid>8fa10a95-de88-403b-8f63-2fee09cb2023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-member-0&quot;)/div[@class=&quot;big-page column-container center-x-flex center-y-flex shrink-flex edges-flex&quot;]/div[@class=&quot;column-container edges-flex max-width max-height&quot;]/div[3]/div[@class=&quot;small-padding-right small-padding-left&quot;]/div[@class=&quot;nav-search-div&quot;]/input[@id=&quot;searchInput&quot;]</value>
      <webElementGuid>c04ad65e-62f4-4048-b475-22b727f35711</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='searchInput'])[2]</value>
      <webElementGuid>ba8d7302-dd1b-4ce9-9cba-fca6f94d4c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-member-0']/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>77b46319-080b-4e0c-adba-00ea7c8ad76d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>f75d8569-bfcb-47ba-928e-a7cf125dfaa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'searchInput' and @name = 'searchText' and @placeholder = 'Pesquisar']</value>
      <webElementGuid>bd48ba4d-3c17-4de7-88b7-e0a5e68e075e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
