<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnput_Lista-Sexta-feira</name>
   <tag></tag>
   <elementGuidId>e7d8ebb4-de72-4acd-87ae-5801fdbb1eec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='9d344c53-539b-4272-9ac3-41b1e0018c5d']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#9d344c53-539b-4272-9ac3-41b1e0018c5d</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Lista de Sexta-feira&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1821170-a06d-478c-8d45-cfb40d26fd56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>listaId</value>
      <webElementGuid>8c52ad02-14e5-4f41-a10e-2053af9d9481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9d344c53-539b-4272-9ac3-41b1e0018c5d</value>
      <webElementGuid>4c29a73c-02c7-4ba0-acad-9a97ef8bba96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a3345018-1034-40b0-8775-3a7ad26d5f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>9d344c53-539b-4272-9ac3-41b1e0018c5d</value>
      <webElementGuid>b90b5b18-5d9f-42be-a13d-dc7a382eee85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-list-0&quot;)/div[@class=&quot;big-page column-container center-x-flex center-y-flex shrink-flex edges-flex&quot;]/form[@class=&quot;column-container edges-flex max-width max-height&quot;]/div[@class=&quot;column-container wrap-flex small-gap center-x-flex small-padding-right small-padding-left list-chooser&quot;]/div[1]/input[@id=&quot;9d344c53-539b-4272-9ac3-41b1e0018c5d&quot;]</value>
      <webElementGuid>57fa2007-63e1-43d9-904a-77ea164e56a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='9d344c53-539b-4272-9ac3-41b1e0018c5d']</value>
      <webElementGuid>02788333-a8b1-4c7a-a6bd-e89f4652d5c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-list-0']/div/form/div[2]/div/input</value>
      <webElementGuid>aa4b6ab9-5aef-4b5c-ba03-a99892b3f35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>021cd984-9be4-4811-b426-9c2508aeadc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'listaId' and @id = '9d344c53-539b-4272-9ac3-41b1e0018c5d' and @type = 'radio']</value>
      <webElementGuid>f758942f-9942-498d-8900-89f3439cca92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
