<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Membros_Permission</name>
   <tag></tag>
   <elementGuidId>f5ba087c-a513-46c8-b0ae-cd867928f5e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@name='editPermissions'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>07d382f6-e9c3-4317-8630-a1d41dc987cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>editPermissions</value>
      <webElementGuid>f63ca3e3-d15a-46a3-adbf-6d15476bcf19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>permissions-0</value>
      <webElementGuid>8d6877f3-3d71-433e-8fbf-973b6a5fdce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Leitor
                                                    Editor
                                                    Leitor
                                                </value>
      <webElementGuid>2bbe88fe-7852-4c0c-bfc4-ecafccbbdea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-container&quot;)/div[@class=&quot;column-container smaller-gap-y&quot;]/div[@class=&quot;background-constrast-color-2 rounded-border max-width&quot;]/div[@class=&quot;max-width open background-constrast-color-2&quot;]/div[@class=&quot;small-margin-right small-margin-left small-margin-bottom small-margin-top smaller-gap-y column-container&quot;]/div[@class=&quot;background-constrast-color small-padding tiny-gap-y column-container rounded-border&quot;]/div[@class=&quot;row-container edges-flex max-width&quot;]/div[@class=&quot;column-container max-width&quot;]/div[@class=&quot;row-container edges-flex max-width&quot;]/div[@class=&quot;editPermisions&quot;]/select[1]</value>
      <webElementGuid>c59080c2-89f5-48e2-a046-9d94f3e51a6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@name='editPermissions'])[2]</value>
      <webElementGuid>938760c9-9d46-4239-8e3f-663db65d6dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-container']/div[4]/div/div[2]/div/div[5]/div[3]/div/div[3]/div[2]/select</value>
      <webElementGuid>39e2565e-d118-45fc-b838-8cf83f6206b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecionar Permissão:'])[2]/following::select[1]</value>
      <webElementGuid>b98e3c5e-6451-428c-b927-3ad7f941bbba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Util'])[1]/following::select[1]</value>
      <webElementGuid>fe5b1f40-719e-44fd-9f81-ace1f0bb00bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adicionar um Membro'])[1]/preceding::select[1]</value>
      <webElementGuid>264873ac-525e-431a-8ce5-c3759035bcf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesquise um membro'])[1]/preceding::select[1]</value>
      <webElementGuid>7d9d81b8-700d-4bba-9015-7fd9b0b21537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>8692be61-489d-41ae-a310-6ddaa29553e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'editPermissions' and @form = 'permissions-0' and (text() = '
                                                    Leitor
                                                    Editor
                                                    Leitor
                                                ' or . = '
                                                    Leitor
                                                    Editor
                                                    Leitor
                                                ')]</value>
      <webElementGuid>5704a3ab-05ce-40c1-afe4-4e23c7ebd42b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
