<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Escolha uma categoria               _8ff80a</name>
   <tag></tag>
   <elementGuidId>51e61bb5-d7d2-4a0a-81cb-1e84626f6db3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ProdCategoria']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ProdCategoria</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Categoria&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d240ea9c-4640-4081-9c05-82ebe042632b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f792c55a-0e73-423e-ae87-d1171d89e220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>85cb89b0-7ed2-4238-866a-841d397e035e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Categoria field is required.</value>
      <webElementGuid>e3255d28-03de-425c-ab7e-4199566a4b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProdCategoria</value>
      <webElementGuid>c03acaf8-1894-41b8-8a2a-738c13c7d04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProdCategoria</value>
      <webElementGuid>290329db-aac2-4127-8fb2-5ac8ee2b2b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Escolha uma categoria
                        Enlatados
Frescos
Biologicos
Congelados
Pastelaria
Talho
Peixaria
Charcutaria
Bebidas
Vegan
Doces
Snacks
BebidasAlcoólicas
</value>
      <webElementGuid>27480b14-92c3-4381-a81a-f294e23181ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProdCategoria&quot;)</value>
      <webElementGuid>7f201eed-d470-427e-8997-abb5e6fdc7a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ProdCategoria']</value>
      <webElementGuid>0e94f1f7-0bfc-408d-92ad-a15e590da2ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categoria'])[1]/following::select[1]</value>
      <webElementGuid>180efc29-daa8-42d6-bbb3-67fd5d2fff8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peso'])[1]/following::select[1]</value>
      <webElementGuid>765cb809-0e1d-468b-8329-63483c7a4a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personalizar por loja'])[1]/preceding::select[1]</value>
      <webElementGuid>5002162e-6222-45f8-81c5-1df501afc7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adicionar Foto'])[1]/preceding::select[1]</value>
      <webElementGuid>54265427-341d-4c92-a028-b01a5c68f793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>e95928d9-9dee-42ae-b7a3-37135b2408b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ProdCategoria' and @name = 'ProdCategoria' and (text() = '
                            Escolha uma categoria
                        Enlatados
Frescos
Biologicos
Congelados
Pastelaria
Talho
Peixaria
Charcutaria
Bebidas
Vegan
Doces
Snacks
BebidasAlcoólicas
' or . = '
                            Escolha uma categoria
                        Enlatados
Frescos
Biologicos
Congelados
Pastelaria
Talho
Peixaria
Charcutaria
Bebidas
Vegan
Doces
Snacks
BebidasAlcoólicas
')]</value>
      <webElementGuid>eaca7398-3522-4ce3-ba19-908c72c808f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
