<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Escolha uma unidade                 _2a5e59</name>
   <tag></tag>
   <elementGuidId>2b4e24b6-3530-4705-9bb9-cbfc0a632291</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7cc510bd-0b86-4e62-b0ba-6f284bd442da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>58b12845-912e-4abd-8ad9-9263f9474315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>whatUnit()</value>
      <webElementGuid>3779cde0-24b8-46a3-90c4-41a0f9f22fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>73889213-e484-48d8-8b24-3f47c29a457d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>499fbbfd-70ab-4c21-80dc-68c8a7462b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Unidade field is required.</value>
      <webElementGuid>8150f0fb-6a68-4049-b3a6-cc794909c8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Unidade</value>
      <webElementGuid>547d073e-fcfd-4ad1-a343-b4379b5e133c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Escolha uma unidade
                            Kg
Unit
Liter
</value>
      <webElementGuid>f5c432a8-d978-40be-b873-8b53881f3efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select&quot;)</value>
      <webElementGuid>a9509213-3859-429a-8376-6d8db6762a05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select']</value>
      <webElementGuid>d73b98e4-23d7-4ba8-bb0e-fc5b5949b095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unidade'])[1]/following::select[1]</value>
      <webElementGuid>5bffe577-eae5-4ea0-a23e-1cfdeb8b20cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preço(€)'])[1]/following::select[1]</value>
      <webElementGuid>9bb8610a-af66-4aab-a828-cbf950ead8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peso'])[1]/preceding::select[1]</value>
      <webElementGuid>c99b633e-aef7-4c11-a1fa-ad7a7c57775b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categoria'])[1]/preceding::select[1]</value>
      <webElementGuid>636fd528-e2f0-4ac6-9e0a-17f8f9589ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6b91d71e-236a-4135-a0e3-67484a417606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'select' and @name = 'Unidade' and (text() = '
                                Escolha uma unidade
                            Kg
Unit
Liter
' or . = '
                                Escolha uma unidade
                            Kg
Unit
Liter
')]</value>
      <webElementGuid>be43c375-7eaf-4449-9293-daa03807add1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
