<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continuar_Comerciante</name>
   <tag></tag>
   <elementGuidId>5d521d67-36d5-4f43-b501-744708f24fcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'register-comerciante-submit' and @type = 'submit' and @href = '/Identity/Account/RegisterComerciante' and (text() = 'Continuar' or . = 'Continuar')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='register-comerciante-submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#register-comerciante-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Continuar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e8a94b1-f15f-47a6-8ddc-baf73ef04938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register-comerciante-submit</value>
      <webElementGuid>610d39fd-2810-4a6a-905d-5fb27e050625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>79f35dda-ba47-46c6-801d-9e604bb8a5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pechincha-button main-button-color</value>
      <webElementGuid>d46af9d3-126b-4a90-8b0c-ff41854e3fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Identity/Account/RegisterComerciante</value>
      <webElementGuid>0a3398a4-b96b-4f33-aaa3-911b70e7d30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>fb218f3b-f26a-406c-8f98-d008e5d6114e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register-comerciante-submit&quot;)</value>
      <webElementGuid>52636413-ce1d-42bc-9930-ba11ae21f396</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='register-comerciante-submit']</value>
      <webElementGuid>418ec3d9-8acc-4782-9464-6ad59e9e1793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Continuar')])[2]</value>
      <webElementGuid>1aa5c1c8-2d2f-4620-adc7-5ee7f8aca3c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continuar'])[2]/following::a[1]</value>
      <webElementGuid>ffbd086a-e47d-47e6-a15f-aa1a20184064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continuar'])[1]/following::a[2]</value>
      <webElementGuid>32675a16-dd6a-43af-8e70-5b056b91f64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Identity/Account/RegisterComerciante')]</value>
      <webElementGuid>22854081-891d-48c9-a876-cd0069d87242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>cedb5ff2-8bfe-4504-a379-018819eaabdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'register-comerciante-submit' and @type = 'submit' and @href = '/Identity/Account/RegisterComerciante' and (text() = 'Continuar' or . = 'Continuar')]</value>
      <webElementGuid>72d38924-8499-4d02-8fdc-3674c6519723</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
