<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Editar</name>
   <tag></tag>
   <elementGuidId>87531541-2fe1-439b-ac54-7202cacc3b23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='preferencesEditableField(this)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#preferences-form > div.row-container.smaller-gap-x > div.pechincha-button.default-button-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#preferences-form >> internal:text=&quot;Editar&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>71d4619e-2076-4e5f-ac01-e4abe2d6e3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pechincha-button default-button-color</value>
      <webElementGuid>92ee9477-bc84-4c21-a7d8-ee52662de520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>preferencesEditableField(this)</value>
      <webElementGuid>e22a5d95-40f8-4909-9a69-18bd7dc8110c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Editar</value>
      <webElementGuid>048d2675-cb56-437c-93ef-861e624749d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preferences-form&quot;)/div[@class=&quot;row-container smaller-gap-x&quot;]/div[@class=&quot;pechincha-button default-button-color&quot;]</value>
      <webElementGuid>c51671b3-0f68-4c27-bc96-8b599241f318</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='preferencesEditableField(this)']</value>
      <webElementGuid>eace31e3-022e-4c5c-974b-e61b7c0e702a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='preferences-form']/div[2]/div</value>
      <webElementGuid>22edd98b-85cb-41ad-b819-aae8b48096f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salvar'])[5]/following::div[1]</value>
      <webElementGuid>3715ed2b-17df-4445-a159-49ab5fad11d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BebidasAlcoólicas'])[1]/following::div[2]</value>
      <webElementGuid>568843d8-9731-46ca-a7a5-5bd08b73de67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/form/div[2]/div</value>
      <webElementGuid>461a6ee4-19d5-4c5d-bebc-b83ea0bcdefc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Editar' or . = 'Editar')]</value>
      <webElementGuid>bfd1dabe-319c-4217-b949-84ccd87fdd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='phoneEditableField(this)']</value>
      <webElementGuid>03bf9f0a-c35a-4848-acdf-7737718d3135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='change-phone-form']/div[2]/div</value>
      <webElementGuid>6744e6ae-1ba6-47d6-bc00-32615364ff73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salvar'])[4]/following::div[1]</value>
      <webElementGuid>a5e8e2aa-c0b8-4637-950c-74ae7f636e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacto'])[1]/following::div[2]</value>
      <webElementGuid>cc8ff885-0a56-47ad-bbb4-747c0b205416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/div[2]/div</value>
      <webElementGuid>7ca051dd-2517-425a-83dc-01937017a702</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
