<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Editar_Input.UserPhone</name>
   <tag></tag>
   <elementGuidId>d5aabfa1-6df9-4a96-b560-5394020551f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phone-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phone-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#phone-input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c2e845b-617e-4e67-bad6-839ad24679cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone-input</value>
      <webElementGuid>b007c35f-a377-451a-af21-4fb836d8ca4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Por favor escolha o seu nome.</value>
      <webElementGuid>7b4dade4-054e-48dd-91e5-0f5ac266fdb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8f85e4f8-00d9-4e37-ab8a-71da4632cfed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6f85f3ae-08ee-404f-9f82-7e7bdfc842d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Contacto field is required.</value>
      <webElementGuid>d009467e-cfc8-43b6-a34e-b3e87784e78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Input.UserPhone</value>
      <webElementGuid>2c10a9a5-7125-4b9f-9d40-f836b66445ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>123456787</value>
      <webElementGuid>19baa399-f20a-4695-a47c-9f6a5b483510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone-input&quot;)</value>
      <webElementGuid>9d92de79-32a0-4860-ac3d-c74773329317</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phone-input']</value>
      <webElementGuid>a06c59b1-c41f-40fe-81fd-03274d8f19f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='change-phone-form']/div/input</value>
      <webElementGuid>c8722595-dff1-40ad-8384-66735567effb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/div/input</value>
      <webElementGuid>8f6f58b7-e69c-4275-8f2d-83b182be11c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'phone-input' and @placeholder = 'Por favor escolha o seu nome.' and @type = 'number' and @name = 'Input.UserPhone']</value>
      <webElementGuid>df608215-4ce4-4d0d-bcd9-be544a4abe00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
