<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Editar_Input.UserPhone</name>
   <tag></tag>
   <elementGuidId>d5aabfa1-6df9-4a96-b560-5394020551f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phone-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phone-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#phone-input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86e8d113-c6b3-4a2b-973d-5598221fc5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone-input</value>
      <webElementGuid>53d243bc-949e-448e-a9ff-c1d2915a81b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Por favor escolha o seu nome.</value>
      <webElementGuid>60807110-89e7-40f4-a9ae-ca6c45a0c870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>420671ed-ad76-4c7c-808e-656db8ab8456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>04658934-7ff1-4913-921b-9aed14f2bbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Contacto field is required.</value>
      <webElementGuid>9bf77cbb-3deb-4b3e-b847-ba6aab3264a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Input.UserPhone</value>
      <webElementGuid>7a4b8b0d-1ca7-4c1c-b200-2bddaeeff184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>932465871</value>
      <webElementGuid>9fe55f1a-f117-4719-b20b-8c97ad9725f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone-input&quot;)</value>
      <webElementGuid>078ad29f-ae3c-4ae9-bb01-1bd72b61087d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phone-input']</value>
      <webElementGuid>bfec23b8-a61d-41b8-b231-b4ad720e4ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='change-phone-form']/div/input</value>
      <webElementGuid>7befecef-5811-4953-be2d-55b6324521c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/div/input</value>
      <webElementGuid>ccf8d9f3-fa5f-4572-ad3b-0bf2e7c2dde6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'phone-input' and @placeholder = 'Por favor escolha o seu nome.' and @type = 'number' and @name = 'Input.UserPhone']</value>
      <webElementGuid>e48baba2-6891-4d64-b7e9-d992f78d3497</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
