<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Editar_Input.Location</name>
   <tag></tag>
   <elementGuidId>14fafabf-01ae-4e28-9fe5-582e9a2eab6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#location-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='location-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Please choose your phone number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>824ec246-0d77-4728-9438-84cdb4135f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>location-input</value>
      <webElementGuid>aea06556-e93d-4f59-a658-e6ea4c61fdc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please choose your phone number</value>
      <webElementGuid>57ecae54-2625-4713-af6f-2e89eead25cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b148aa5-bcee-4f37-a6b9-5284ae64e8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c3a5ecd8-6999-418f-85f0-ffadffa6e655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Localização field is required.</value>
      <webElementGuid>928da8e3-5fd5-4b3b-8d16-fbd8502d9d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Input.Location</value>
      <webElementGuid>977c3ebe-1e4b-42c1-acc8-13276459435f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Setúbal</value>
      <webElementGuid>9a946a88-c0db-491b-a981-f3ea0406231e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location-input&quot;)</value>
      <webElementGuid>3d4a26b1-51e3-403c-ae7d-749ff094d3a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='location-input']</value>
      <webElementGuid>90d4d908-9db1-44d0-af91-de7813c7d530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='location-form']/div/input</value>
      <webElementGuid>7946b7da-8ae9-4998-9585-04a53ac0f4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/div/input</value>
      <webElementGuid>4e1bcdac-5fd5-4fed-9bc5-820d9f62c786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'location-input' and @placeholder = 'Please choose your phone number' and @type = 'text' and @name = 'Input.Location']</value>
      <webElementGuid>d5b247ff-7daf-41e5-892c-6f4b2ef9c645</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
