<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Pastelaria</name>
   <tag></tag>
   <elementGuidId>aaa6b831-4825-4295-8d49-796201411002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='preferences-form']/div/div/div[5]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Pastelaria&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d09ccbd3-dc0c-483f-af41-7eaa9c5fffe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>preference_4</value>
      <webElementGuid>71956964-7848-4368-b255-d6b293e00727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pastelaria</value>
      <webElementGuid>44d01424-b54f-4dd6-8f22-1113fece2512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preferences-form&quot;)/div[1]/div[@class=&quot;row-container wrap-flex small-gap preferences-parent&quot;]/div[@class=&quot;edit-checkbox&quot;]/label[1]</value>
      <webElementGuid>9c48fb91-09a9-440f-a816-7673119365af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='preferences-form']/div/div/div[5]/label</value>
      <webElementGuid>ab3b05a6-fe78-471a-a97b-2e50cba527cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Congelados'])[1]/following::label[1]</value>
      <webElementGuid>c10357a8-88d4-47ad-a423-9f0aca5b80ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biologicos'])[1]/following::label[2]</value>
      <webElementGuid>81c4319c-5c2b-44f4-ac7b-9ed41429df4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Talho'])[1]/preceding::label[1]</value>
      <webElementGuid>5af13226-21f6-42fe-ab25-16c7a3393b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peixaria'])[1]/preceding::label[2]</value>
      <webElementGuid>4b2df58d-ff3f-4ac4-97d4-97bc37d9e29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pastelaria']/parent::*</value>
      <webElementGuid>9464c4e8-dfa8-4e1a-ab6e-2371d96cfbc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label</value>
      <webElementGuid>343ecd12-db6b-4d71-91d1-88c72a4d3219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Pastelaria' or . = 'Pastelaria')]</value>
      <webElementGuid>d5177664-ed7d-4152-9f16-b4ae1cef68e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
