<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Comerciante_comerciantes</name>
   <tag></tag>
   <elementGuidId>f54b288e-a37b-4327-b398-f0eea98ab40c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comerciantes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='comerciantes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#comerciantes</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8eea877d-1f3b-462f-a2c7-dbe477912cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>06b9b384-606b-49d9-8dc0-2cc5b82afb5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ComerciantePMK</value>
      <webElementGuid>99937922-dd92-4dcf-9aae-40dda6046ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comerciantes</value>
      <webElementGuid>7b583493-0902-4cef-9fd2-5b31f10fb757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comerciantes</value>
      <webElementGuid>c1b0ab6a-e569-4631-bc2b-8c8cf5d3c771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>filtrar();</value>
      <webElementGuid>2741238a-85bd-4339-88e1-e89e8d0cd482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comerciantes&quot;)</value>
      <webElementGuid>6ca03460-6d8c-4d6e-adad-497176c6c224</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='comerciantes']</value>
      <webElementGuid>aab9c65e-bb69-48d3-a2b3-73fb654cfaab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>a3eb2aaf-f9ff-4e63-aa8e-15a43b5eac47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'comerciantes']</value>
      <webElementGuid>87a4e132-d02e-48ee-a869-ef607ea0a974</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
