<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Salvar</name>
   <tag></tag>
   <elementGuidId>87e37513-5a4d-4e4f-9d08-8decfa82a977</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#salvarButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='salvarButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Salvar&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>002ccbb7-004f-41f5-8fb3-655589d2c71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pechincha-button main-button-color row-container</value>
      <webElementGuid>3c9997c9-2b6d-47a1-ba9f-975b00ee3bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>salvarButton</value>
      <webElementGuid>2ff0533f-99bb-4f07-b074-f0a544bdacbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salvar</value>
      <webElementGuid>b8468bb3-6d0e-4695-91a0-86f6923a4d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;salvarButton&quot;)</value>
      <webElementGuid>69f09069-6b6f-471b-a327-dd787ccdd783</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='salvarButton']</value>
      <webElementGuid>9cabbe74-8128-4d7d-9460-a6edbec90a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data-select']/div/div[3]/div</value>
      <webElementGuid>6df4deab-8cbd-4113-a669-f67fcbb14cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dezembro'])[1]/following::div[2]</value>
      <webElementGuid>a9debf9f-aa18-48f4-b3f3-fb3680190018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Novembro'])[1]/following::div[4]</value>
      <webElementGuid>99dcd7b0-b0f2-43a5-b776-2ce7d5138825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Salvar']/parent::*</value>
      <webElementGuid>8e6a4a0f-2139-4d4e-8ef7-799a93419464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>4482fa43-3fb1-433b-9201-158e68c8b456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'salvarButton' and (text() = 'Salvar' or . = 'Salvar')]</value>
      <webElementGuid>1cc01415-ac45-4447-9879-995fb93ab463</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
