<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__duration</name>
   <tag></tag>
   <elementGuidId>58aec507-99f6-4f6d-9534-ca970f0c9663</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#duration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='duration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#duration</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7207ef7-1e1b-4156-b08c-d07d01fa1ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd478c24-70b0-47b0-bb73-6ebd21a80ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>duration</value>
      <webElementGuid>103a3c19-f02b-4724-aae5-2dfc65a0b88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>duration</value>
      <webElementGuid>061fcbaa-0fbd-400c-b102-1ca380d3f939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>openDiscountDuration(); clickedInput(this);</value>
      <webElementGuid>330819ae-16b8-43f8-8a24-662e6a0ecfa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value> -</value>
      <webElementGuid>3175a775-ae04-4f88-9492-0f4df443a56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;duration&quot;)</value>
      <webElementGuid>1a43281f-531b-4104-b2b2-1b8434ef065f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='duration']</value>
      <webElementGuid>5d5e81fd-701b-4c70-a012-926103948b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lojas']/table/tbody/tr/td[4]/input</value>
      <webElementGuid>16e1bd1c-8ad3-4bdc-ade7-c26809fe373a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>f73240fb-17c0-45ed-bad6-983205b0ac15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'duration' and @name = 'duration']</value>
      <webElementGuid>fc9c0f1e-d3d0-4ce3-bf97-cafb296ec386</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
