<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__price_1</name>
   <tag></tag>
   <elementGuidId>2bd71296-060a-4fec-b9e7-ead5ab17cb3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#priceInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='priceInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#priceInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a25572d3-06a2-43ea-8b7e-808565b08653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c7d5ee5a-7c71-480c-90cf-ce8ef64fe535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>priceInput</value>
      <webElementGuid>82cad3aa-b275-43dd-8559-f5d780510396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>9346d115-5be6-4a34-98b2-498fbee13ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prices custom-input</value>
      <webElementGuid>28c8ea7e-c881-4228-ad15-e2e2e9f6ca59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2.1</value>
      <webElementGuid>215c7422-314d-4f91-adfa-26ddc0ebcda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0.1</value>
      <webElementGuid>2b4b1ab2-4ed2-4de8-ac22-f6981ff6359e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>999</value>
      <webElementGuid>08bdbb6e-c47c-4a3b-b22d-b90dc427dc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;priceInput&quot;)</value>
      <webElementGuid>ab9e6d90-a738-4fa8-8b41-b42163250d93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='priceInput']</value>
      <webElementGuid>6862e86f-5cda-4f76-ac43-5e0deb8e1baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lojas']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>596dc3e4-a703-4c06-b415-3e9f31b079c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>9351de2a-8ab5-410f-80cb-022ff07a3364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'priceInput' and @name = 'price']</value>
      <webElementGuid>99371900-f466-4991-8de0-199f4c5c057c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
