<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Salvar_Preferencias</name>
   <tag></tag>
   <elementGuidId>0844ac56-6233-4f88-9717-137e7cf8b611</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#preferences-form > div.row-container.smaller-gap-x > button.pechincha-button.main-button-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#preferences-form >> internal:role=button[name=&quot;Salvar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8d231f45-c652-4952-834d-e1151d3abedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>50972b4a-6598-4b25-a87b-4b79d24cc85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pechincha-button main-button-color</value>
      <webElementGuid>068428d3-e901-40f0-9ccb-695f01ca4cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salvar</value>
      <webElementGuid>a09d486d-f6c1-4647-88a5-b303937a7baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preferences-form&quot;)/div[@class=&quot;row-container smaller-gap-x&quot;]/button[@class=&quot;pechincha-button main-button-color&quot;]</value>
      <webElementGuid>3d2129a7-6d5e-4c81-8599-e544235c7212</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[8]</value>
      <webElementGuid>53fdb334-719b-47ab-b4a1-3336615f9a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='preferences-form']/div[2]/button</value>
      <webElementGuid>753312c1-8082-4993-b2be-de60070773c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BebidasAlcoólicas'])[1]/following::button[1]</value>
      <webElementGuid>37748095-4ae9-4fbc-b02f-82fd621e1e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Snacks'])[1]/following::button[1]</value>
      <webElementGuid>46c6a23b-e894-40ec-a634-8812d37fe228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[3]/preceding::button[1]</value>
      <webElementGuid>a561a7ac-78d1-4c38-8889-b9b9bbed5955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/form/div[2]/button</value>
      <webElementGuid>7beaa88b-fff6-4b5d-bd08-23569a936de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Salvar' or . = 'Salvar')]</value>
      <webElementGuid>276c8c33-4204-4fae-883e-721824daeb5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
