<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Editar_Email</name>
   <tag></tag>
   <elementGuidId>2f7751ba-1a35-4d2f-807a-9be017d0f7ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='displayEditableField(this)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email-form > div.row-container.center-y-flex.smaller-gap-x > div.pechincha-button.default-button-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#email-form >> internal:text=&quot;Editar&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>053cca59-62cb-4b54-82f8-dcc7d580cb15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pechincha-button default-button-color</value>
      <webElementGuid>12b9f78c-4abd-42bf-920a-6b680445926f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>displayEditableField(this)</value>
      <webElementGuid>dcdef1fc-d8e9-4f9d-8309-606ea51922cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Editar</value>
      <webElementGuid>74f146fb-85be-4aae-938a-713ab6af5247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-form&quot;)/div[@class=&quot;row-container center-y-flex smaller-gap-x&quot;]/div[@class=&quot;pechincha-button default-button-color&quot;]</value>
      <webElementGuid>704a885b-e95a-445e-89a6-84fb8109d2bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='displayEditableField(this)']</value>
      <webElementGuid>80903057-61ec-4dcb-b51b-ff36b0c01a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='email-form']/div[2]/div</value>
      <webElementGuid>ea79c929-599c-440f-a140-754750dcfc0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mudar Email'])[1]/following::div[1]</value>
      <webElementGuid>1c249400-ce15-41c3-9fbb-280fec2b44cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Novo email'])[1]/following::div[2]</value>
      <webElementGuid>f5fe0e11-3b60-48e8-b4c0-64880467c648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password atual'])[1]/preceding::div[1]</value>
      <webElementGuid>a6359ece-3b37-43cb-91b9-83627ca5ab03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nova password'])[1]/preceding::div[2]</value>
      <webElementGuid>f4bbe89d-3338-4d3c-b4be-94dd2a3655c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[2]/div</value>
      <webElementGuid>855f1389-39fd-4ee9-8eea-cab6b418e23b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Editar' or . = 'Editar')]</value>
      <webElementGuid>cdfb446e-fc05-491d-aace-1607ff6c615b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
