<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UserPhone</name>
   <tag></tag>
   <elementGuidId>c475493c-e4d1-4783-8345-5b517f92d777</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phone-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phone-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#phone-input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba8330d2-d7c9-4eb3-bba5-b41be54fade2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone-input</value>
      <webElementGuid>bb898432-2d6a-4882-99a7-3f2d5321b4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Por favor escolha o seu nome.</value>
      <webElementGuid>f96e58d5-5fdf-45d0-8f0b-1c9601a42864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>bb19598e-718b-406c-a318-926f1e39259f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5c853afc-4b18-4fe9-a5e7-571972ff736e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Contacto field is required.</value>
      <webElementGuid>0f501fe2-9cd4-4fb0-ae51-e913ed20598c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Input.UserPhone</value>
      <webElementGuid>20274072-8e40-4ab0-862e-837c0deec9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>123456785</value>
      <webElementGuid>531402e2-a473-4020-b5a4-7cb7e6b9d521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone-input&quot;)</value>
      <webElementGuid>5c3b4e4a-255d-4edd-ad6a-480ee31537ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phone-input']</value>
      <webElementGuid>d714cf15-3493-4652-ac04-aa87ce33f1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='change-phone-form']/div/input</value>
      <webElementGuid>2ab25156-f56c-47f8-b6b6-0271691f96ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/div/input</value>
      <webElementGuid>6941afcb-6956-479b-a4b0-7cb8cc7d1586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'phone-input' and @placeholder = 'Por favor escolha o seu nome.' and @type = 'number' and @name = 'Input.UserPhone']</value>
      <webElementGuid>59b107b2-372b-471f-9acc-15dfbb73dce2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
