<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Enlatados</name>
   <tag></tag>
   <elementGuidId>00a1505a-20eb-4d40-9fac-7dac8111b459</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='preferences-form']/div/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.edit-checkbox > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Enlatados&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>902206b0-0f6f-4ebd-ad64-f15b91ed0b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>preference_0</value>
      <webElementGuid>a3068316-832a-4c12-a793-7789a3790f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enlatados</value>
      <webElementGuid>37b12cf7-62af-4b9a-8759-81552c4f5c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preferences-form&quot;)/div[1]/div[@class=&quot;row-container wrap-flex small-gap preferences-parent&quot;]/div[@class=&quot;edit-checkbox&quot;]/label[1]</value>
      <webElementGuid>2c1b8d58-0adf-4e53-a2f5-47e3b044fec4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='preferences-form']/div/div/div/label</value>
      <webElementGuid>00dfbc93-d89d-4904-8921-02b03a085b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preferências'])[1]/following::label[1]</value>
      <webElementGuid>e796dadc-11ce-4401-b9ba-d8cda1114726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[4]/following::label[2]</value>
      <webElementGuid>b6aba5d6-981f-4cc0-b71e-138a592ca704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frescos'])[1]/preceding::label[1]</value>
      <webElementGuid>9db9eaa3-3e59-441c-bdca-c059dad19be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biologicos'])[1]/preceding::label[2]</value>
      <webElementGuid>2c58225f-a80e-4161-ad12-ffcf9ab9e682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enlatados']/parent::*</value>
      <webElementGuid>460adfe3-5d6e-4f4b-9426-438d945a114d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/label</value>
      <webElementGuid>a8ccfef3-8717-490e-b083-41737c0218d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Enlatados' or . = 'Enlatados')]</value>
      <webElementGuid>fa8ffd13-4012-4e3a-919f-4a08f4a6da9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
