<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_photo-option-2</name>
   <tag></tag>
   <elementGuidId>e0c6b399-72f5-4fc5-addb-83caa409257a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='change-photo-form']/div[2]/span[10]/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>span:nth-child(10) > label > .big-perfil-image</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cc46df0e-b0d0-41a0-83d8-cab9e64ede54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>big-perfil-image perfil-image-border</value>
      <webElementGuid>78a7621b-694a-4b3c-8803-77fc435cdf03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;change-photo-form&quot;)/div[@class=&quot;wrap-flex small-gap center-x-flex small-padding-right small-padding-left photo-chooser&quot;]/span[@class=&quot;photo-option&quot;]/label[1]/span[@class=&quot;big-perfil-image perfil-image-border&quot;]</value>
      <webElementGuid>6a2c3372-5745-412d-a6fd-5442ef4ad38c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='change-photo-form']/div[2]/span[10]/label/span</value>
      <webElementGuid>f185f484-bdbc-43da-a492-5866b3af9797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[10]/label/span</value>
      <webElementGuid>3b9258e8-fbff-4d55-b0df-e1b8c9ca8a54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
