<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout_cursor-pointer small-image nav-lin_58ce0e</name>
   <tag></tag>
   <elementGuidId>d1d5a230-c962-42a6-81ff-a457d4fd0f58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href, '/ListaProdutos')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.pechincha-navbar-option.cursor-pointer.small-image.nav-link.text-dark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b04bf4ed-5aca-456e-91db-14c4af964813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pechincha-navbar-option cursor-pointer small-image nav-link text-dark</value>
      <webElementGuid>c8acb1e3-bc64-45fe-8c52-3afa036b1ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ListaProdutos</value>
      <webElementGuid>2fad7f30-1df0-489a-838d-4b1203981526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[1]/nav[@class=&quot;navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 small-padding-left small-padding-right&quot;]/div[@class=&quot;edges-flex max-width small-gap-x center-y-flex&quot;]/div[@class=&quot;max-width display-flex center-y-flex small-gap-x pechincha-navbar&quot;]/div[@class=&quot;display-flex small-gap-x&quot;]/a[@class=&quot;pechincha-navbar-option cursor-pointer small-image nav-link text-dark&quot;]</value>
      <webElementGuid>b04cf618-ad0d-4504-8fff-59679af2d493</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ListaProdutos')]</value>
      <webElementGuid>274bde38-b436-40b3-96ae-dcdc64e1986d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>fa7e10f8-ec07-4c5a-a91d-5da28273cf8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ListaProdutos']</value>
      <webElementGuid>094cca83-042b-4b07-ae66-e3b7a0dc914e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>013d80cc-c747-4b9f-b30a-ee4872f88fb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
