<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Perfil</name>
   <tag></tag>
   <elementGuidId>3f3f3b62-bb01-4fbd-acbf-34eec1abcc23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.move-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='perfil-menu']/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Perfil&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3642e2c2-8596-444b-9a16-0913b63e97d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>move-text</value>
      <webElementGuid>98d0e9e0-176d-4f43-bf05-56ab76055d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Perfil</value>
      <webElementGuid>cfaeda35-305a-4489-8c9d-787950972299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;perfil-menu&quot;)/div[1]/a[@class=&quot;pechincha-navbar-option pechincha-link&quot;]/span[@class=&quot;move-text&quot;]</value>
      <webElementGuid>140bd62d-4e01-4854-a523-64a18487d0e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='perfil-menu']/div/a/span</value>
      <webElementGuid>43e502c9-f189-4ef3-91f1-467146e8cbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terminar Sessão'])[1]/preceding::span[1]</value>
      <webElementGuid>e6f6c2ac-7492-4f86-8f3e-a5c042af1f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Perfil']/parent::*</value>
      <webElementGuid>eaa421bf-0f7b-4310-8a63-77e9883932d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a/span</value>
      <webElementGuid>e58daab6-4daa-4373-804e-700552dd08a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Perfil' or . = 'Perfil')]</value>
      <webElementGuid>fdd4d855-2b7f-45e6-b052-958fe89c442d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
